### ISSUE TITLE
Suggestion: Add lifecycle callbacks to support having loading indicators

### ISSUE THREAD

**Issue by carlosflorencio** [dpayne/CodeGPT.nvim#12]
Hi,

Thanks for the plugin :), since it can take a few seconds to have the ChatGPT response it would be cool have some sort of UI loading feedback (e.g statusline loading spinner). 

I suggest having some callbacks like:
```lua
vim.g["codegpt_hooks"] = {
  request_started = function() 
   -- update some ui, start a spinner
  end,

  request_finished = function()
   -- update some ui, stop the spinner
  end
}
```

A lualine component would be 🔥 .

**Comment by dpayne** [comment]
This is a good idea. I will try to work on adding it when I get a chance (pull requests are always welcome : )

**Comment by roobert** [comment]
Hey, I had an initial go at adding loading status to the plugin - this doesn't seem to work very well but may be a starting point for someone else to continue from! https://github.com/dpayne/CodeGPT.nvim/pull/16

The idea is to insert a random ID into a table everytime the plugin is executed, that way if multiple executions are made, `Loading` is still displayed until the last callback has completed. This could also be used to display the number of running executions in the statusbar, or something.

I load this into the `lualine` statusline with:
```
lvim.builtin.lualine.on_config_done = function(lualine)
	local config = lualine.get_config()
	table.insert(config.sections.lualine_x, 1, { require("CodeGPT").status })
	lualine.setup(config)
end
```

**Comment by 00sapo** [comment]
Tested and for me works, but after modifications (see my comments in the pull request for adjusting it)

**Comment by dpayne** [comment]
done with this PR https://github.com/dpayne/CodeGPT.nvim/commit/9b9e02addf862ba0ff782638382c4eb2495cdb17

**Comment by carlosflorencio** [comment]
Thanks @dpayne !
