### ISSUE TITLE
Feature Request: Horizontal Buffer Output

### ISSUE THREAD

**Issue by whobutsb** [dpayne/CodeGPT.nvim#14]
Would it be possible to make the ChatGPT output show up in a new horizontal buffer?  This would make it easier to review the output and copy and paste what is needed back in to the project that I'am working. 

Thanks for creating the plugin.  It's been fun to experiment with ChatGPT.

**Comment by dpayne** [comment]
Do you have an example of what you mean? Maybe a plugin that does something similar?

**Comment by dpayne** [comment]
@whobutsb  would this work https://github.com/dpayne/CodeGPT.nvim#move-completion-to-popup-window?

**Comment by whobutsb** [comment]
Sure, i'll give that a try.  I was kind of envisioning something like you type in `:help [command]` and it opens up a new horizontal buffer window and it displays the text.

**Comment by dpayne** [comment]
Finally got around to doing this, https://github.com/dpayne/CodeGPT.nvim/pull/34. Please feel free to re-open if it either has issues or doesn't do what you want/described.
