### ISSUE TITLE
ChatGPT think my selection is not valid YAML

### ISSUE THREAD

**Issue by tito** [dpayne/CodeGPT.nvim#17]
I have a yaml file where i want to reformulate some texts, or ensure there is no grammar error in my description.
If i select one sentence, and ask ChatGPT to reformulate, it tells me that it is not valid YAML.

Example:
```yaml
info:
  title: Example
  version: '1.0'
  description: |
    Bienvenue sur la documentation XXX. Cette API vous permet de contrôler YYY et ZZZ.
```

If i select just the line with "Bienvenue", and ask:

```
:Chat Corrige la phrase
```

The output will be:

I'm sorry, but the given input is not a valid YAML code snippet. YAML is a data serialization language and requires proper indentation and syntax.

Is there a way to avoid the yaml tagging of the selection ?

**Comment by dpayne** [comment]
I'm closing this as I think this is not an issue with the plugin but with what ChatGPT outputted. If I am incorrect, please let me know.
