### ISSUE TITLE
What's the difference with ChatGPT.nvim?

### ISSUE THREAD

**Issue by 00sapo** [dpayne/CodeGPT.nvim#19]
To my understanding, the only true difference is that CodeGPT implements actions from lua snippets, while ChatGPT also allows external json to be loaded, plus a number of utilities, UI, etc.

Is there any other difference?

**Comment by dpayne** [comment]
I assume you mean https://github.com/jackMort/ChatGPT.nvim. The project looks great and there's nothing wrong with it. For me, the main difference is the overall goals. ChatGPT.nvim seems to be aiming for more of a full interaction with ChatGPT within nvim. What I wanted was something where the code complete was very simple and still customizable.

**Comment by 00sapo** [comment]
I'm not saying any of the projects is wrong or better than the other. I currently use both of them because both of them have some issues in my config.

With this issue, I just wanted to point out that the "customizability" point is already available in ChatGPT.nvim, even if not documented yet (I discovered it looking at the code) by using external json and, of course, by overriding lua methods that return tables.

In my exploration, the only big difference is that CodeGPT.nvim uses chat-3.5-turbo while ChatGPT.nvim is using davinci for most tasks, and I haven't found an easy way for the user to change it to chat-3.5-turbo. However, as newer models will come out, this will surely change in the near future for both the two plugins, so I wouldn't consider this aspect a fundamental difference (moreover, chat-3.5-turbo and davinci are comparable from the effectiveness perspective).

I think it is important to have clear what are objectives, not to spread too much work across different projects, and, instead, to create plugins that complement each other... :)
