### ISSUE TITLE
Feature Request: chat question 

### ISSUE THREAD

**Issue by madnight** [dpayne/CodeGPT.nvim#32]
Please add a question command:

| command      | input | Description |
|--------------|---- |------------------------------------|
| question  |  text selection and command args| Will ask ChatGPT a question (the command args) to the selected code. |

I think this is a quiet frequent use case. We already have "explain" but this offers a generic explanation and not a specific explanation to a given question for selected code.

**Comment by dpayne** [comment]
Good idea, done!
