### ISSUE TITLE
Language instructions appear to be ignored

### ISSUE THREAD

**Issue by brandoncazander** [dpayne/CodeGPT.nvim#33]
Hi there, thanks for making this neat plugin! I have been trying to add language instructions as per the README but haven't had much luck. When following the [Example configuration](https://github.com/dpayne/CodeGPT.nvim#example-configuration) section to add instructions to use pytest for python tests, it appeared to not be respected:

```lua
require("codegpt.config")

vim.g["codegpt_commands"] = {
  ["tests"] = {
    language_instructions = {
        python = "Use the pytest unit framework",
    },
  }
}
```

Adding a print for debugging showed that the prompt didn't include these instructions, it said the following (two spaces between the sentences point to the language_instructions template not being rendered):

> Write really good unit tests using best practices for the given language.  Only return the unit tests. 

I did confirm that the buffer I was in had the appropriate filetype.

I was able to get it working with this configuration; is the documentation out of date or is this a bug? (using [this functionality](https://github.com/dpayne/CodeGPT.nvim/blob/58c21bb98249fe18ee399aee2f0f1b1d5dc73bcf/lua/codegpt/template_render.lua#L26))

```lua
vim.g.codegpt_lang_instructions_python_tests = "Use the pytest test framework."
```

Would be happy to try and contribute a fix if you think this is worth fixing. Thanks!

**Comment by dpayne** [comment]
this should be fixed now, let me know if you still notice issues

**Comment by brandoncazander** [comment]
Works great; thanks for the fix!
