### ISSUE TITLE
Use tiktoken to estimate message tokens

### ISSUE THREAD

**Issue by harjotgill** [dpayne/CodeGPT.nvim#36]
OpenAI's definition of tokens is different from the length of the message. The models have much larger token capacity than message length-based limts.

See - https://github.com/openai/tiktoken

**Comment by blockchainian** [comment]
hey @dpayne! i am running into the token limit, too. happy to take a look at this if you haven't got to it!

**Comment by harjotgill** [comment]
For reference, see how I use tiktoken in the PR review GitHub action - https://github.com/fluxninja/openai-pr-reviewer
