### ISSUE TITLE
Text does not wrap around in the popup by default

### ISSUE THREAD

**Issue by jaime10a** [dpayne/CodeGPT.nvim#4]
When using nvim with the setting `vim.o.wrap = false`, the popup that appears when using the Chat command `:Chat hello world` does also not wrap the text around.
This is probably expected behavior, but for this use case, I think no one would use it without wrapping, so setting wrapping to true by default on this popup window would probably be better.
![Screenshot 2023-03-08 at 20 50 53](https://user-images.githubusercontent.com/53908430/223832214-04cd3686-0a4b-4d0b-8fa6-2987c4c39069.png)

**Comment by dpayne** [comment]
merged https://github.com/dpayne/CodeGPT.nvim/pull/5
