### ISSUE TITLE
 attempt to index upvalue 'CodeGptModule' (a boolean value) 

### ISSUE THREAD

**Issue by dtrckd** [dpayne/CodeGPT.nvim#43]
Hi,

I am getting this error I am calling :Chat since https://github.com/dpayne/CodeGPT.nvim/pull/42 I guess.

```
.vim/bundle/CodeGPT.nvim/plugin/codegpt.lua:5: attempt to index upvalue 'CodeGptModule' (a boolean value) 
```

**Comment by dtrckd** [comment]
Yes,

I've found out that the error happen if you have a file named `codegpt.lua` in your lua config file, even though it is never call.

`touch ~/.config/nvim/lua/codegpt/lua`
`vim -c "Chat test"`

**Comment by yuchanns** [comment]
This is the default behavior of Neovim's Lua module search mechanism.
FYI: https://neovim.io/doc/user/lua.html#require().
This is not a bug IMO.

**Comment by dtrckd** [comment]
mmh, I see I its more a nvim/vim question, that maybe sould trigger a warning if a user defined config file conflict with a plugin why.

Thanks for the feedback.
