### ISSUE TITLE
Feature request: generate command

### ISSUE THREAD

**Issue by TamaMcGlinn** [dpayne/CodeGPT.nvim#45]
Please add a generate command:

command | input | Description
-- | -- | --
generate | command args | Will ask ChatGPT to generate the command args in the language of the buffer

This is like completion in that it only outputs the code and puts that into the buffer, but without requiring any existing code. For example, if I open a new file and do `:Chat generate fibonacci function` it should insert a function called fibonacci with the appropriate implementation in the language indicated by the language of the buffer.

**Comment by dpayne** [comment]
this was a good idea, should be available in main now. Thank you!
