### ISSUE TITLE
Enable custom commands with args and without text selection

### ISSUE THREAD

**Issue by TamaMcGlinn** [dpayne/CodeGPT.nvim#48]
lua/codegpt.lua makes it clear that when there is no text selection, but there are args, then the command must be chat. Why is that?

> ```
>     if text_selection ~= "" and command_args ~= "" then
>         local cmd_opts = CommandsList.get_cmd_opts(command)
>         if cmd_opts ~= nil and has_command_args(cmd_opts) then
>             command_args = table.concat(opts.fargs, " ", 2)
>         elseif cmd_opts and 1 == #opts.fargs then
>             command_args = ""
>         else
>             command = "code_edit"
>         end
>     elseif text_selection ~= "" and command_args == "" then
>         command = "completion"
>     elseif text_selection == "" and command_args ~= "" then
>         command = "chat"
>     end
> ```

For example, this custom command will not work, unless you select some arbitrary whitespace first:

```lua
vim.g["codegpt_commands"] = vim.tbl_extend("force", vim.g["codegpt_commands"] or {}, 
  {
    ["eli"] = {
        system_message_template = "You are a tutor to a ten year old child. Explain everything using simple English.",
        user_message_template = "{{command_args}}",
        callback_type = "text_popup",
    }
})
```

I would expect doing `:Chat eli how are cars made?` to use the custom template, but it actually just reverts to "you are a general assistant to a software developer". This behaviour works if I select some whitespace and do `:'<,'>Chat eli how are cars made?`

A current workaround is to define your own command that directly calls run_cmd with the right command name:

```lua
vim.api.nvim_create_user_command("Eli", function(opts)
    require("codegpt.commands").run_cmd("eli", table.concat(opts.fargs, " "), "")
end, {range = true, nargs = "*"})
```

Now `:Eli how are cars made?` works as expected. This shouldn't be necessary.

**Comment by dpayne** [comment]
The reason for this was I ran into some situations where was asking a question but the first word overlapped with an existing command. For example, if you added the command "hello", then asked a question "hello chat?" it would trigger the hello command.

As a fix, I've added a command option `allow_empty_text_selection`. That doesn't really fix the command/first word overlap but hopefully it should limit the amount of times it happens.
