### ISSUE TITLE
Feature: automatically pull token definitions in the codebase into the context when the token is selected.

### ISSUE THREAD

**Issue by nmnduy** [dpayne/CodeGPT.nvim#51]
It would be nice to have the class/function, etc. definitions pulled into the context when we select some code.

Features:

- When we select some code, find the definition of the class, functions, etc. in the codebase and put it into the context. Might require an external tool to achieve this.
- Make this feature optional.

Additional thoughts:

- If the function body is too large, maybe we should reduce the content of the function.
- Add a parameter to limit how many class/function definitions to include in the context.

**Comment by dpayne** [comment]
This would require a lot of work and I am not sure it makes sense in this plug. The goal here was something fairly simple.

It would make sense to integrate as part of something larger that is already parsing the code (e.g. coc.nvim).
