### ISSUE TITLE
Autocompleted result is broken

### ISSUE THREAD

**Issue by raine** [dpayne/CodeGPT.nvim#8]
Hello. Any idea why this might be happening? Sometimes the result is correct, but half the time you get this broken result.

Is there a way to debug actual API response to see if the problem is with the autocompleted result and not in the way plugin replaces the selected lines with the ChatGPT result?

https://user-images.githubusercontent.com/11027/223973493-d43174fc-c2de-4c09-93ca-15c0693b4752.mp4

  
Thanks!

**Comment by dpayne** [comment]
Can you add this to your lua config somewhere after loading the plugins?

```lua
require("codegpt.config")

vim.g["codegpt_commands"] = {
["completion"] = {
    callback_type = "code_popup",
},
}

```

That will switch to loading the results in a popup window instead.

**Comment by raine** [comment]
Thanks. The response from OpenAI API appears to be 

```json
{
  "id": "chatcmpl-6sAtJR1wRwAU0zNJQzEpiKUGvalkj",
  "object": "chat.completion",
  "created": 1678369597,
  "model": "gpt-3.5-turbo-0301",
  "usage": {
    "prompt_tokens": 83,
    "completion_tokens": 57,
    "total_tokens": 140
  },
  "choices": [
    {
      "message": {
        "role": "assistant",
        "content": "```function getTitle(): Promise<string> {\n  return http.get(\"http://example.com\").then((body) => {\n    const regex = /<title>(.*?)<\\/title>/;\n    const result = regex.exec(body);\n    return result[1];\n  });\n}```"
      },
      "finish_reason": "stop",
      "index": 0
    }
  ]
}
```

Will try to look into why that is happening.

**Comment by dpayne** [comment]
That works when the user has added a comment. I think it's a good idea but I'm also super lazy : ) and I often use the completion without writing any comments. I'll see if maybe I can change the prompt based on if there are comments. Meanwhile, that is one of the reason why I really wanted it easy for people to customize the prompts, everyone has different workflows.
